### PR TITLE
feat: added QB in signoz-features sidebar

### PR DESCRIPTION
**Pull request by Calm-Rock**

### CODE REVIEW

**Comment by makeavish** [comment]
@Calm-Rock Please resolve conflict

**Comment by Calm-Rock** [comment]
> @Calm-Rock Please resolve conflict

Done @makeavish

**Comment by makeavish** [comment]
Adding @ankit01-oss to review this, I think the description can be better here.

**Comment by Calm-Rock** [comment]
@makeavish 

Please approve and merge it for now - will take feedback separately from @ankit01-oss

**Review by makeavish — APPROVED** [review]

**Pull request merged**
