### PR TITLE
docs: 📝 SigNoz address grid

### LINKED ISSUE #724: K8s- Docker - VM IP grid
Currently there is a lot of confusion on which IP to use to send data to signoz. Multiple scenarios lead to different IPs to connect to signoz. We shall share a matrix of scenarios depending on where signoz is installed and where is the application running.

SigNoz can run in:
- [ ] docker-compose
- [ ] kubernetes

Application can run in:
- [ ] a VM with vanilla deployment instructions
- [ ] a VM with docker-compose
- [ ] k8s

### PR DESCRIPTION
**Pull request by prashant-shahi**
Resolves https://github.com/SigNoz/signoz/issues/724

- Added SigNoz Otel Collector address grid with html table
- Added generic APITable component  from docusaurus

/cc @ankitnayan
/cc @palash-signoz

Signed-off-by: Prashant Shahi <prashant@signoz.io>

### CODE REVIEW

**Comment by pranay01** [comment]
@prashant-shahi the column and row headers are not very clear. Can this be edited to something like below?

Troubleshooting SigNoz 2022-02-16 at 12 47 44 PM

**Comment by prashant-shahi** [comment]
@pranay01 Official markdown spec doesn't support merging cells.
We can opt out for including an image instead of text.

**Comment by prashant-shahi** [comment]
@pranay01  I have replaced Markdown table with html table tag with minor css changes.

**Comment by pranay01** [comment]
Nice. LGTM

**Pull request merged**
