### PR TITLE
Feat: Typescript support is added

### PR DESCRIPTION
**Pull request by palashgdev**
Typescript support is added

### CODE REVIEW

**Comment by pranay01** [comment]
@palash-signoz What does this PR do ?

**Comment by pranshuchittora** [comment]
@pranay01 this is PR adds support for TypeScript. Currently all the code in this repo is written in pure JavaScript, with the support for TS we can slowly shift towards TS which can reduce a lot of possible bugs during dev time.

**Review by pranshuchittora — APPROVED** [review]

**Comment by pranshuchittora** [comment]
Codeowners pls merge this when everything gets resolved. Good Day

**Review by pranay01 — APPROVED** [review]

**Comment by pranay01** [comment]
> @pranay01 this is PR adds support for TypeScript. Currently all the code in this repo is written in pure JavaScript, with the support for TS we can slowly shift towards TS which can reduce a lot of possible bugs during dev time.

Got it

**Pull request merged**
