### PR TITLE
Added OCI Cold Bucket Integration doc By Sudhanshu Dev

### PR DESCRIPTION
**Pull request by sudhanshud**
Added OCI Cold Bucket Integration doc.
- Added docs/tutorial/oci-bucket-cold-storage-integration.md file.
- Added Static Images.

### CODE REVIEW

**Review by sudhanshud — COMMENTED** [review]
Fixed the image issue

**Review by sudhanshud — COMMENTED** [review]
Incorprated PR review feedback

**Review by sudhanshud — COMMENTED** [review]
Fixed formatting issues

**Review by prashant-shahi — APPROVED** [review]
@sudhanshud Great work  🎉

**Comment by prashant-shahi** [comment]
@Calm-Rock Can you also include the minimal follow-through version of this tutorial under [retention period docs](https://signoz.io/docs/userguide/retention-period/)?

**Comment by Calm-Rock** [comment]
> @Calm-Rock Can you also include the minimal follow-through version of this tutorial under [retention period docs](https://signoz.io/docs/userguide/retention-period/)?

@prashant-shahi do you want me to hyperlink this under the retention period docs ?
If yes can you point out where should I put it for now?

**Comment by prashant-shahi** [comment]
Just a new section for OCI Object Storage and minimal instructions in the retention period docs should do.

And in the end add link to tutorial for detailed steps.

**Pull request merged**
