### PR TITLE
Update the description for external and db calls

### LINKED ISSUE #341: Add details on docs on what type of services will come in External Calls tab in metrics page
- [ ] Will DynamoDB calls appear as external calls?
- [ ] Will S3 calls appear as external calls?
- [ ] Will call to another service appear as external call?

What is the mechanism by which SigNoz identifies what will appear in External calls?

Screenshot 2022-06-02 at 8 13 26 PM

### PR DESCRIPTION
**Pull request by srikanthccv**
Fixes #341

### CODE REVIEW

**Comment by pranay01** [comment]
@srikanthccv This should be merged with `0.10.0` release right?

**Comment by srikanthccv** [comment]
@pranay01 Yes, these changes are being shipped with `0.10.0`.

**Comment by pranay01** [comment]
@srikanthccv Have merged this though it seems it is written in a complicated way. 

e.g. `rpc.system, rps.service, rpc.method`
Does this mean all of these attributes should be present at the same time or even if one of the attributes is present then the external tab would be populated

Screenshot 2022-07-15 at 11 32 15 PM

**Comment by srikanthccv** [comment]
>Does this mean all of these attributes should be present at the same time or even if one of the attributes is present then the external tab would be populated

Among the listed sets of attributes, at least one set must fully present. If you think wording is not obvious please update it.

**Pull request merged**
