### PR TITLE
Docs/send metrics

### LINKED ISSUE #124: localhost is not accessible from docker container
The example target in Prometheus receiver shows using `localhost:8080` as a target but localhost is not accessible from inside of otel-collector container. What would be a good way to solve this?

https://signoz.io/docs/userguide/send-metrics/#enable-a-prometheus-receiver

### PR DESCRIPTION
**Pull request by prashant-shahi**
Resolves SigNoz/signoz-web#124

### CODE REVIEW

**Comment by prashant-shahi** [comment]
@pranay01 can you review and merge this PR?

**Comment by ankit01-oss** [comment]
@prashant-shahi is this still relevant or should I close this?

**Comment by prashant-shahi** [comment]
@ankit01-oss it is still relevant. Feel free to merge it.

**Comment by Calm-Rock** [comment]
@prashant-shahi can you please resolve conflicts - we can merge this PR post that and migrate to https://github.com/SigNoz/signoz-web

**Comment by prashant-shahi** [comment]
@Calm-Rock Conflicts resolved, can you review and merge this PR?

**Review by Calm-Rock — APPROVED** [review]

**Pull request merged**
