### PR TITLE
Troubleshooting faqs

### PR DESCRIPTION
**Pull request by ankit01-oss**

### CODE REVIEW

**Comment by pranay01** [comment]
@ankit01-oss one of the points have number, others don't

Also, I think the service map point should be last or 2nd last. other points are more common

Screenshot 2022-09-08 at 12 52 15 PM

**Comment by ankit01-oss** [comment]
@pranay01 on it. Also, resolving the deploy issue. Don't merge this for now.

**Comment by ankit01-oss** [comment]
@pranay01 this can be merged now.

**Comment by ankit01-oss** [comment]
@pranay01 merging it myself as I need to take a new pull.

**Pull request merged**
