### PR TITLE
docs(otlp-cors): 📝 tutorial to enable CORS in OTLP HTTP receiver

### PR DESCRIPTION
**Pull request by prashant-shahi**
Signed-off-by: Prashant Shahi <prashant@signoz.io>

### CODE REVIEW

**Comment by pranay01** [comment]
@prashant-shahi Can we find a better place for it in the docs structure rather than the top level. Doesn't see like that big a topic to put a new top level section IMO

CORS

**Comment by prashant-shahi** [comment]
> @prashant-shahi Can we find a better place for it in the docs structure rather than the top level. Doesn't see like that big a topic to put a new top level section IMO

@pranay01 I thought of including it under apm/metrics/logs section but did not since it is relevant for all of them.
Alternative would be tutorials section for this.

**Comment by ankit01-oss** [comment]
Let's do it under `Configurations`? @pranay01 @prashant-shahi

Screenshot 2023-04-03 at 5 42 07 PM 

This is important for browser instrumentation too. We have then instructions mentioned in our blogs for angular and react.

**Comment by prashant-shahi** [comment]
@pranay01 @ankit01-oss Moved the page to Configuration section.

**Pull request merged**
