### PR TITLE
Upgrade to docusaurus v3

### LINKED ISSUE #1214: Upgrade to docusaurus v3.0
We should monitor when docusaurus v3.0 is released to GA. Might have some perf improvements and better customization.
Though it has many breaking changes, so we should update only when it is stable.

Below is their beta release for v3.0

https://github.com/facebook/docusaurus/releases/tag/v3.0.0-beta.0

cc @ankit01-oss @Calm-Rock

### PR DESCRIPTION
**Pull request by pranay01**
Facing issues around mdx like, will need manual work to solve the issues shown in MDX (20+ issues)

mdx-issues

Closes https://github.com/SigNoz/signoz.io/issues/1214

### CODE REVIEW

**Comment by pranay01** [comment]
Guides for migration - https://docusaurus.io/docs/migration/v3

**Comment by pranay01** [comment]
Fixes https://github.com/SigNoz/signoz.io/issues/1214

**Comment by zriyansh** [comment]
what if I take it up? Have good experience debugging mdx @pranay01 @ankit01-oss

**Comment by pranay01** [comment]
> what if I take it up? Have good experience debugging mdx @pranay01 @ankit01-oss

@zriyansh We are working on improving the docs currently, so may be we will take this up after that. Don't want to have too many moving pieces

**Comment by Calm-Rock** [comment]
Closing this PR since we have migrated to the [new website](https://github.com/SigNoz/signoz-web) not based on Docusaurus.

**Pull request closed without merging**
